#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5  

xinput set-prop "Asus TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "Asus TouchPad" "libinput Natural Scrolling Enabled" 1
nitrogen --restore
picom --experimental-backends &
killall dunst & #Restart Dunst
~/.config/eww/target/release/eww daemon
xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh

bspc config border_width         3
bspc config focused_border_color \#B3DEFF
bspc config normal_border_color \#3C3836
bspc config window_gap          14

bspc config focus_follows_pointer true
bspc config top_padding 30
bspc config bottom_padding 0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^4' state=floating follow=off


